# Dashboard
# http://localhost:6333/dashboard
#
# Create a collection with default dense vector
# curl  -X PUT \
#   'http://localhost:6333/collections/VintageStoreIndex' \
#   --header 'Content-Type: application/json' \
#   --data-raw '{ "vectors": { "size": 384, "distance": "Cosine" } }'
#
services:
  qdrant:
    image: docker.io/qdrant/qdrant:v1.14.1
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - .qdrant:/qdrant/storage:z
